# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mode
      MONGO_INITDB_DATABASE: trades
    ports:
      - 27017:27017
    restart: unless-stopped
